Adds feature to create/update keystore with new key pair

diff --git a/contents/keytoolw b/contents/keytoolw
--- a/contents/keytoolw
+++ b/contents/keytoolw
@@ -12,11 +12,12 @@ options_parse() {
     do
         OPT="$1"
         case "$OPT" in
-        	--action)        action=$2        ; shift 2 ;;
-            --jdk-home)      jdk_home=$2      ; shift 2 ;;
-            --keystore-path) keystore_path=$2 ; shift 2 ;;
-            --cert-path)     cert_path=$2     ; shift 2 ;;
-			--age-thresh)	 age_thresh=$2    ; shift 2 ;;
+        	--action)        		action=$2        		; shift 2 ;;
+            --jdk-home)      		jdk_home=$2      		; shift 2 ;;
+            --keystore-path)		keystore_path=$2 		; shift 2 ;;
+            --cert-path)     		cert_path=$2     		; shift 2 ;;
+			--age-thresh)			age_thresh=$2    		; shift 2 ;;
+			--overwrite-keystore)   overwrite_keystore=$2	; shift 2 ;;
             # help option
             -\?|--help)
                 usage
@@ -128,14 +129,14 @@ action:checkExp() {
 	# How many days between today and $expDate?
 	secondsDiff=$(( `date -d $expDate +%s` - `date +%s` ))
 	daysDiff=$( echo $secondsDiff/86400 | bc )
-	echo "Your certificate expires in $daysDiff days."
+	printf "%s\n" "Your certificate expires in $daysDiff days."
 
 	if [[ -n "$ageThresh" ]]
 	then
 		# check against specified threshhold and fail if necessary
 		if [[ "$daysDiff" -le "$ageThresh" ]]
 		then
-			printf "%s" "It's time to renew your certficate for $alias!" 1>&2
+			printf "%s\n" "It's time to renew your certficate for $alias!" 1>&2
 			exit 3
 		else
 			:
@@ -145,11 +146,37 @@ action:checkExp() {
 	fi
 
 }
+action:create() {
+	# Build the arguments list
+	local keytoolOut=''
+	local keystore=$1 alias=$2 storePass=$3 keyPass=$4 keyAlg=$5 keySize=$6 cn=$7 ou=$8 org=$9 
+	local loc=${10} state=${11} country=${12} validPd=${13} san=${14} overwrite=${15}
+
+	local dname=`printf "%s" \"CN="$cn", OU="$ou", O="$org", L="$loc", S="$state", C="$country"\"`
+	local clopts=( -genkeypair -noprompt -alias "$alias" -keyalg "$keyAlg" -keysize "$keySize" -keystore "$keystore" -dname "$dname" )
+	clopts+=( -validity "$validPd" -storepass \""$storePass"\" -keypass \""$keyPass"\" )
+	[[ -n "$san" ]] && clopts+=( -ext san="$san")
+
+	# Delete the keystore if it already exists and user checked override flag
+	if [[ -e "$keystore" ]] && [[ "$overwrite" = "true" ]]
+	then
+		printf "%s\n" "The keystore $keystore already exists. Deleting."
+		rm -f "$keystore" || { printf "%s\n" "Error deleting keystore." 1>&2; exit 1; }
+	else
+		:
+	fi
+
+	# Create keystore
+	printf "%s\n" "Creating new keystore: $keystore"
+	keytoolOut=$(eval $keytool "${clopts[@]}") || { echo $keytoolOut; exit 1; }
+
+}
 
 #Begin script execution
 
-declare -r actions=(list printcert checkExp)
+declare -r actions=(list printcert checkExp create)
 declare -r keystore_password="${RD_CONFIG_KEYSTORE_PASSWORD:-}"
+declare -r private_key_password="${RD_CONFIG_PRIVATE_KEY_PASSWORD:-}"
 
 if ! options_parse "$@"
 then
@@ -168,6 +195,9 @@ case "$action" in
 	;;	
 	checkExp)
 		action:checkExp "$keystore_path" "${RD_CONFIG_ALIAS:-}" "$keystore_password" "$age_thresh"
+	;;
+	create)
+		action:create "$keystore_path" "${RD_CONFIG_ALIAS:-}" "$keystore_password" "$private_key_password" "${RD_CONFIG_KEY_ALG:-}" "${RD_CONFIG_KEY_SIZE:-}" "${RD_CONFIG_COMMON_NAME:-}" "${RD_CONFIG_ORG_UNIT:-}" "${RD_CONFIG_ORG_NAME:-}" "${RD_CONFIG_LOC_NAME:-}" "${RD_CONFIG_STATE_NAME:-}" "${RD_CONFIG_COUNTRY:-}" "${RD_CONFIG_VALIDITY_PERIOD:-}" "${RD_CONFIG_SAN:-}" "$overwrite_keystore"
 	;;
 	*) usage
 	;;
